# Trigger on pull request to master (+ allow manual runs of this workflow)
# Checkout repo, install Node.js, run test

name: pr-workflow

on:
[pull-request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        name : Hello World!
        run : echo Hello world 
        
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install Node.js
        run: npm index.js
        
